package net.hunnor.dict.android.task;

public enum ExtractTaskStatus {

    E_STREAM_FILE_NOT_FOUND,

    E_STREAM_ASSET_NOT_FOUND,

    E_DEPLOY_DELETE_DEPLOY_INDEX_DIR,

    E_DEPLOY_DELETE_DEPLOY_SPELLING_DIR,

    E_DEPLOY_DELETE_INDEX_DIR,

    E_DEPLOY_DELETE_SPELLING_DIR,

    E_DEPLOY_RENAME_INDEX_DIR,

    E_DEPLOY_RENAME_SPELLING_DIR,

    E_DEPLOY_REOPEN_INDEX,

    E_DEPLOY_ZIP_EXTRACT,

    E_DOWNLOAD_DELETE,

    E_EXCEPTION_IO,

    OK

}
